use super::tokens::KeyToken;

#[allow(non_camel_case_types)] // This silences the warning
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum KbPosition {
    // Left hand - outside (pinky) in, top to bottom
    L_C0_R0,
    L_C0_R1,
    L_C0_R2,
    L_C0_R3,
    L_C0_R4,
    L_C1_R0,
    L_C1_R1,
    L_C1_R2,
    L_C1_R3,
    L_C1_R4,
    L_C2_R0,
    L_C2_R1,
    L_C2_R2,
    L_C2_R3,
    L_C2_R4,
    L_C3_R0,
    L_C3_R1,
    L_C3_R2,
    L_C3_R3,
    L_C3_R4,
    L_C4_R0,
    L_C4_R1,
    L_C4_R2,
    L_C4_R3,
    L_C4_R4,
    L_C5_R0,
    L_C5_R1,
    L_C5_R2,
    L_C5_R3,
    L_C6_R0,
    L_C6_R1,
    L_C6_R2,
    // Left Thumb Cluster
    // The two large vertical keys (2U)
    L_Thumb_2U_Outer,
    L_Thumb_2U_Inner,
    // The four regular keys (1U) forming the '7' around the inner large key
    L_Thumb_1U_TopOuter,
    L_Thumb_1U_TopInner,
    L_Thumb_1U_MidInner,
    L_Thumb_1U_BottomInner,

    // Right hand
    R_C0_R0,
    R_C0_R1,
    R_C0_R2,
    R_C0_R3,
    R_C0_R4,
    R_C1_R0,
    R_C1_R1,
    R_C1_R2,
    R_C1_R3,
    R_C1_R4,
    R_C2_R0,
    R_C2_R1,
    R_C2_R2,
    R_C2_R3,
    R_C2_R4,
    R_C3_R0,
    R_C3_R1,
    R_C3_R2,
    R_C3_R3,
    R_C3_R4,
    R_C4_R0,
    R_C4_R1,
    R_C4_R2,
    R_C4_R3,
    R_C4_R4,
    R_C5_R0,
    R_C5_R1,
    R_C5_R2,
    R_C5_R3,
    R_C6_R0,
    R_C6_R1,
    R_C6_R2,
    // Right Thumb Cluster
    // The two large vertical keys (2U)
    R_Thumb_2U_Outer,
    R_Thumb_2U_Inner,
    // The four regular keys (1U) forming the 'backwards 7' around the inner large key
    R_Thumb_1U_TopOuter,
    R_Thumb_1U_TopInner,
    R_Thumb_1U_MidInner,
    R_Thumb_1U_BottomInner,
}

#[expect(dead_code)]
#[derive(Debug, Clone)]
pub enum KeyAction {
    /// basic remap
    Remap(&'static KeyToken),

    /// macro: {trigger}>{action1}{action2}...
    /// using vec to hold ordered list due to variable macro length
    Macro(Vec<&'static KeyToken>),

    /// tap and hold: [position]>[tap][t&hXXX][hold]
    TapAndHold {
        tap: &'static KeyToken,
        delay_ms: u16,
        hold: &'static KeyToken,
    },
}

#[expect(dead_code)]
#[derive(Debug, Clone)]
pub struct KbKey {
    pub position: KbPosition,
    pub default_token: &'static KeyToken,
}

impl KbPosition {
    pub fn get_position(default_pos_value: &str) -> Option<KbPosition> {
        match default_pos_value {
            "eql" => Some(KbPosition::L_C0_R0),
            "tab" => Some(KbPosition::L_C0_R1),
            "esc" => Some(KbPosition::L_C0_R2),
            "lshf" => Some(KbPosition::L_C0_R3),
            "lfn" => Some(KbPosition::L_C0_R4),
            "1" => Some(KbPosition::L_C1_R0),
            "q" => Some(KbPosition::L_C1_R1),
            "a" => Some(KbPosition::L_C1_R2),
            "z" => Some(KbPosition::L_C1_R3),
            "grav" => Some(KbPosition::L_C1_R4),
            "2" => Some(KbPosition::L_C2_R0),
            "w" => Some(KbPosition::L_C2_R1),
            "s" => Some(KbPosition::L_C2_R2),
            "x" => Some(KbPosition::L_C2_R3),
            "caps" => Some(KbPosition::L_C2_R4),
            "3" => Some(KbPosition::L_C3_R0),
            "e" => Some(KbPosition::L_C3_R1),
            "d" => Some(KbPosition::L_C3_R2),
            "c" => Some(KbPosition::L_C3_R3),
            "left" => Some(KbPosition::L_C3_R4),
            "4" => Some(KbPosition::L_C4_R0),
            "r" => Some(KbPosition::L_C4_R1),
            "f" => Some(KbPosition::L_C4_R2),
            "v" => Some(KbPosition::L_C4_R3),
            "rght" => Some(KbPosition::L_C4_R4),
            "5" => Some(KbPosition::L_C5_R0),
            "t" => Some(KbPosition::L_C5_R1),
            "g" => Some(KbPosition::L_C5_R2),
            "b" => Some(KbPosition::L_C5_R3),
            "keyt" => Some(KbPosition::L_C6_R0),
            "hk1" => Some(KbPosition::L_C6_R1),
            "hk2" => Some(KbPosition::L_C6_R2),
            "khBB" => Some(KbPosition::L_Thumb_2U_Outer),
            "bspc" => Some(KbPosition::L_Thumb_2U_Inner),
            "lctr" => Some(KbPosition::L_Thumb_1U_TopOuter),
            "lalt" => Some(KbPosition::L_Thumb_1U_TopInner),
            "home" => Some(KbPosition::L_Thumb_1U_MidInner),
            "end" => Some(KbPosition::L_Thumb_1U_BottomInner),
            "hyph" => Some(KbPosition::R_C0_R0),
            "bsls" => Some(KbPosition::R_C0_R1),
            "apos" => Some(KbPosition::R_C0_R2),
            "rshf" => Some(KbPosition::R_C0_R3),
            "rfn" => Some(KbPosition::R_C0_R4),
            "0" => Some(KbPosition::R_C1_R0),
            "p" => Some(KbPosition::R_C1_R1),
            "scol" => Some(KbPosition::R_C1_R2),
            "fsls" => Some(KbPosition::R_C1_R3),
            "cbrk" => Some(KbPosition::R_C1_R4),
            "9" => Some(KbPosition::R_C2_R0),
            "o" => Some(KbPosition::R_C2_R1),
            "l" => Some(KbPosition::R_C2_R2),
            "perd" => Some(KbPosition::R_C2_R3),
            "obrk" => Some(KbPosition::R_C2_R4),
            "8" => Some(KbPosition::R_C3_R0),
            "i" => Some(KbPosition::R_C3_R1),
            "k" => Some(KbPosition::R_C3_R2),
            "comm" => Some(KbPosition::R_C3_R3),
            "down" => Some(KbPosition::R_C3_R4),
            "7" => Some(KbPosition::R_C4_R0),
            "u" => Some(KbPosition::R_C4_R1),
            "j" => Some(KbPosition::R_C4_R2),
            "m" => Some(KbPosition::R_C4_R3),
            "up" => Some(KbPosition::R_C4_R4),
            "6" => Some(KbPosition::R_C5_R0),
            "y" => Some(KbPosition::R_C5_R1),
            "h" => Some(KbPosition::R_C5_R2),
            "n" => Some(KbPosition::R_C5_R3),
            "ss" => Some(KbPosition::R_C6_R0),
            "hk3" => Some(KbPosition::R_C6_R1),
            "hk4" => Some(KbPosition::R_C6_R2),
            "spc" => Some(KbPosition::R_Thumb_2U_Outer),
            "ent" => Some(KbPosition::R_Thumb_2U_Inner),
            "rctr" => Some(KbPosition::R_Thumb_1U_TopOuter),
            "rwin" => Some(KbPosition::R_Thumb_1U_TopInner),
            "pgup" => Some(KbPosition::R_Thumb_1U_MidInner),
            "pgdn" => Some(KbPosition::R_Thumb_1U_BottomInner),
            _ => None,
        }
    }
}
